"""CSV (CIC-IDS2017 format) input path + the unified input contract.

pandas only — no scapy, GPU, LLM or network. Uses the committed sample
data/sample_csv/cicids2017_sample.csv (generated by agentmeter/ingest/sample.py
from rows already in data/cicids_full_300.csv) and the 300-row dataset itself.
"""
from __future__ import annotations

import hashlib
import importlib.util
import json

import pandas as pd
import pytest

from agentmeter.config import PROJECT_ROOT
from agentmeter.ingest import csv_input, rules, run, unified
from agentmeter.ingest.csv_input import CsvValidationError, load_csv
from agentmeter.ingest.feature_map import CIC_FEATURES
from agentmeter.ingest.sample import (EXPECTED_CSV_ROWS, EXPECTED_CSV_USABLE,
                                      build_sample_csv_text)
from agentmeter.ingest.unified import SELECTED_COLUMNS, InputContractError, load_input_run

SAMPLE = PROJECT_ROOT / "data" / "sample_csv" / "cicids2017_sample.csv"
DATASET = PROJECT_ROOT / "data" / "cicids_full_300.csv"
CLASSES = {"Benign", "Brute Force", "DoS Hulk", "Port Scanning", "Volumetric DDoS"}


def _db_hashes() -> dict[str, str]:
    return {str(p): hashlib.sha256(p.read_bytes()).hexdigest()
            for p in (PROJECT_ROOT / "results").glob("*.db")}


def test_committed_sample_matches_the_generator():
    assert SAMPLE.read_text(encoding="utf-8") == build_sample_csv_text()


# --- valid labelled CSV: accuracy available ------------------------------------------
def test_labelled_csv_validates_and_reports_schema_and_classes():
    data = load_csv(SAMPLE)
    rep = data.report
    assert rep["rows_read"] == EXPECTED_CSV_ROWS == 43
    assert rep["rows_usable"] == EXPECTED_CSV_USABLE == 40
    assert rep["rows_dropped_nan_inf"] == 1                       # the 'Infinity' row
    assert rep["label"]["excluded_out_of_taxonomy"] == {"DoS slowloris": 2}
    assert rep["columns"]["present"] == 78 and rep["columns"]["missing"] == []
    assert rep["label"]["found"] and rep["label"]["column"] == "Label"   # raw ' Label' stripped
    assert rep["label"]["distribution"] == {c: 8 for c in CLASSES}
    assert rep["label"]["raw_distribution"]["SSH-Patator"] == 4         # raw -> canonical mapping
    from agentmeter.ingest.feature_map import META_COLUMNS
    assert data.labelled and list(data.features.columns) == META_COLUMNS + CIC_FEATURES


def test_label_is_isolated_from_features_and_from_the_rule_engine(monkeypatch):
    data = load_csv(SAMPLE)
    assert not any(c.lower() == "label" for c in data.features.columns)
    assert list(data.labels.columns) == ["flow_id", "label_raw", "label"]
    assert list(data.labels["flow_id"]) == list(data.features["flow_id"])
    seen = {}
    real = rules.select_flows

    def spy(df, rb, max_flows=None):
        seen["cols"] = list(df.columns)
        return real(df, rb, max_flows=max_flows)

    monkeypatch.setattr(rules, "select_flows", spy)
    run.process_csv(SAMPLE, write=False)
    assert not any(c.lower().startswith("label") for c in seen["cols"])


def test_process_csv_end_to_end_accuracy_available(tmp_path):
    before = _db_hashes()
    res = run.process_csv(SAMPLE, out_root=tmp_path, max_flows=20)
    out = tmp_path / "cicids2017_sample"
    assert sorted(p.name for p in out.iterdir()) == [
        "input.json", "labels.csv", "manifest.json", "schema_report.md",
        "selected_flows.csv", "selection_audit.json"]
    assert _db_hashes() == before and not list(tmp_path.rglob("*.db"))

    meta = json.loads((out / "input.json").read_text())
    assert meta["source_type"] == "csv" and meta["input_role"] == "labelled_csv"
    assert meta["evaluation_mode"] == "accuracy_available"
    assert meta["capabilities"] == {"resource_efficiency": True, "accuracy": True}
    assert meta["feature_match"]["status"] == "exact" and meta["feature_columns"] == CIC_FEATURES
    assert meta["rows_total"] == 40 and meta["rows_selected"] == 20
    assert "label" in meta["hidden_columns"] and "src_ip" in meta["hidden_columns"]
    assert set(meta["label_distribution_selected"]) <= CLASSES
    assert sum(meta["label_distribution_selected"].values()) == 20

    audit = json.loads((out / "selection_audit.json").read_text())
    assert len(audit["flows"]) == 20 and all(f["admitted_by"] and f["reason"] for f in audit["flows"])
    assert "typical_baseline" in audit["rules_fired"]

    sel = pd.read_csv(out / "selected_flows.csv")
    labels = pd.read_csv(out / "labels.csv")
    assert list(sel.columns) == SELECTED_COLUMNS
    assert list(labels["flow_id"]) == list(sel["flow_id"])
    assert "**accuracy_available**" in (out / "schema_report.md").read_text()
    assert res["input"].accuracy_available


def test_canonical_labels_in_the_pipeline_dataset_are_accepted():
    res = run.process_csv(DATASET, write=False)        # lowercase 'label', canonical values
    meta = res["input"].metadata
    assert meta["evaluation_mode"] == "accuracy_available"
    assert res["report"]["rows_usable"] == 300
    assert res["report"]["label"]["distribution"] == {c: 60 for c in CLASSES}
    assert meta["rows_selected"] == 300                # under the 500 budget: all rows kept


def test_unlabelled_csv_is_efficiency_only(tmp_path):
    p = tmp_path / "nolabel.csv"
    pd.read_csv(DATASET).drop(columns=["label"]).head(50).to_csv(p, index=False)
    res = run.process_csv(p, out_root=tmp_path)
    meta = res["input"].metadata
    assert meta["input_role"] == "unlabelled_csv" and meta["evaluation_mode"] == "efficiency_only"
    assert meta["accuracy_unavailable_reasons"] == ["no ground-truth label column"]
    assert not (tmp_path / "nolabel" / "labels.csv").exists()
    assert load_input_run(tmp_path / "nolabel").labels is None


def test_trafficlabelling_identification_columns_become_meta(tmp_path):
    df = pd.read_csv(DATASET).head(30)
    df.insert(0, "Flow ID", "x")
    df.insert(1, "Source IP", "10.0.0.1")
    df.insert(2, "Destination IP", "10.0.0.2")
    df.insert(3, "Protocol", [6] * 20 + [17] * 10)
    p = tmp_path / "full.csv"
    df.to_csv(p, index=False)
    data = load_csv(p)
    assert set(data.features["protocol_name"]) == {"TCP", "UDP"}
    assert data.report["columns"]["extra_ignored"] == [] and data.report["notes"] == []
    assert load_csv(DATASET).report["notes"]            # no Protocol column -> noted


# --- rejections -------------------------------------------------------------------
def _write(tmp_path, name, content):
    p = tmp_path / name
    (p.write_bytes if isinstance(content, bytes) else p.write_text)(content)
    return p


@pytest.mark.parametrize("name, content, msg", [
    ("cap.csv", b"\xd4\xc3\xb2\xa1" + b"\x00" * 40, "packet capture, not a CSV"),
    ("bin.csv", b"PK\x03\x04\x00\x00binary", "binary content"),
    ("empty.csv", "", "empty file"),
    ("other.csv", "name,age,city\nann,3,x\n", "none of the 78 feature columns"),
    ("ragged.csv", "Destination Port,Flow Duration\n1,2\n3,4,5,6\n", "not a readable CSV"),
])
def test_wrong_files_are_rejected_with_a_clear_reason(tmp_path, name, content, msg):
    with pytest.raises(CsvValidationError, match=msg):
        load_csv(_write(tmp_path, name, content))


def test_missing_features_rejected_unless_partial_and_rule_columns_still_required(tmp_path):
    df = pd.read_csv(DATASET).head(40)
    p = tmp_path / "subset.csv"
    df.drop(columns=["Idle Std", "Active Max"]).to_csv(p, index=False)
    with pytest.raises(CsvValidationError, match="2 of 78 CIC-IDS2017 feature columns missing"):
        load_csv(p)
    res = run.process_csv(p, allow_partial=True, write=False)
    meta = res["input"].metadata
    assert meta["feature_match"]["status"] == "partial"
    assert meta["feature_match"]["missing"] == ["Active Max", "Idle Std"]
    assert "Idle Std" not in meta["feature_columns"] and len(meta["feature_columns"]) == 76

    q = tmp_path / "norule.csv"
    df.drop(columns=["Flow Duration"]).to_csv(q, index=False)
    with pytest.raises(CsvValidationError, match="required by the flow-selection rules"):
        run.process_csv(q, allow_partial=True, write=False)


def test_header_only_all_invalid_and_colliding_columns_are_rejected(tmp_path):
    header = ",".join(CIC_FEATURES + ["label"])
    with pytest.raises(CsvValidationError, match="no data rows"):
        load_csv(_write(tmp_path, "h.csv", header + "\n"))
    row = ",".join(["Infinity"] * 78 + ["Benign"])
    with pytest.raises(CsvValidationError, match="no usable rows"):
        load_csv(_write(tmp_path, "inf.csv", header + "\n" + row + "\n"))
    only_oot = pd.read_csv(DATASET).head(5).assign(label="Heartbleed")
    only_oot.to_csv(tmp_path / "oot.csv", index=False)
    with pytest.raises(CsvValidationError, match="out-of-taxonomy"):
        load_csv(tmp_path / "oot.csv")
    with pytest.raises(CsvValidationError, match="collide"):
        load_csv(_write(tmp_path, "dup.csv", "Flow Duration, Flow Duration ,label\n1,2,Benign\n"))


# --- unified contract --------------------------------------------------------------
def test_contract_rejects_label_leak_and_misaligned_labels(tmp_path):
    res = run.process_csv(SAMPLE, out_root=tmp_path, max_flows=10)
    good = res["input"]
    leaked = good.selected.assign(label="x")
    with pytest.raises(InputContractError):
        unified.write_input_run(tmp_path / "bad1", unified.InputRun(good.metadata, leaked, good.labels))
    shuffled = good.labels.iloc[::-1].reset_index(drop=True)
    with pytest.raises(InputContractError, match="align"):
        unified.write_input_run(tmp_path / "bad2", unified.InputRun(good.metadata, good.selected, shuffled))
    loaded = load_input_run(tmp_path / "cicids2017_sample")
    assert loaded.accuracy_available and list(loaded.selected.columns) == SELECTED_COLUMNS


def test_default_output_roots_are_separate_from_the_study_db():
    assert run.DEFAULT_CSV_OUT_ROOT == PROJECT_ROOT / "results" / "csv_runs"
    assert run.DEFAULT_OUT_ROOT == PROJECT_ROOT / "results" / "pcap_runs"
    assert run.detect_input_type(SAMPLE) == "csv"


def _cli():
    spec = importlib.util.spec_from_file_location("ingest_cli", PROJECT_ROOT / "scripts" / "ingest.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_cli_ingests_csv_and_rejects_bad_schema(tmp_path, capsys):
    cli = _cli()
    assert cli.main([str(SAMPLE), "--no-write", "--max-flows", "12"]) == 0
    out = capsys.readouterr().out
    assert "labelled_csv -> accuracy_available" in out and "Selection 12 of 40 rows" in out
    bad = _write(tmp_path, "bad.csv", "a,b\n1,2\n")
    assert cli.main([str(bad), "--no-write"]) == 2
    assert "none of the 78" in capsys.readouterr().err
