"""Phase 47: write web/_headers (Cloudflare Pages) with a strict Content-Security-Policy.

The refresh token lives in localStorage, so the front-end must not run injected script: only
this site's own files and the exact inline scripts of web/index.html and web/analysis.html
(by SHA-256 hash) may run. Re-run after editing an inline script — tests/test_control_plane.py
fails while web/_headers is stale:

    python scripts/csp_headers.py

connect-src allows the Worker (*.workers.dev) and quick tunnels (*.trycloudflare.com). Using a
custom domain for either (a named tunnel, or the Worker on your domain)? Add it to EXTRA_CONNECT
(or the env var AGENTMETER_CSP_CONNECT, space-separated) and re-run.
"""
from __future__ import annotations

import base64
import hashlib
import os
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
WEB = REPO / "web"
PAGES = ("index.html", "analysis.html")
EXTRA_CONNECT: list[str] = []
_INLINE = re.compile(r"<script>(.*?)</script>", re.S)


def script_hashes() -> list[str]:
    out = []
    for page in PAGES:
        for body in _INLINE.findall((WEB / page).read_text(encoding="utf-8")):
            h = "'sha256-" + base64.b64encode(hashlib.sha256(body.encode("utf-8")).digest()).decode() + "'"
            if h not in out:
                out.append(h)
    return out


def csp(extra_connect: list[str] | None = None) -> str:
    extra = list(EXTRA_CONNECT) + (extra_connect if extra_connect is not None
                                   else os.environ.get("AGENTMETER_CSP_CONNECT", "").split())
    connect = " ".join(["'self'", "https://*.workers.dev", "https://*.trycloudflare.com"] + extra)
    return "; ".join([
        "default-src 'self'",
        "script-src 'self' " + " ".join(script_hashes()),
        "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
        "font-src https://fonts.gstatic.com",
        "img-src 'self' data: blob:",
        "connect-src " + connect,
        "frame-src 'self'",
        "frame-ancestors 'self'",
        "base-uri 'none'",
        "form-action 'none'",
        "object-src 'none'",
    ])


def headers() -> str:
    return ("# Cloudflare Pages headers (static site; no Functions). GENERATED by scripts/csp_headers.py —\n"
            "# edit that script (or re-run it after changing an inline script), not this file.\n"
            "/config.json\n  Cache-Control: no-store\n"
            "/*\n"
            "  X-Content-Type-Options: nosniff\n"
            "  Referrer-Policy: strict-origin-when-cross-origin\n"
            "  X-Frame-Options: SAMEORIGIN\n"
            "  Permissions-Policy: camera=(), microphone=(), geolocation=()\n"
            f"  Content-Security-Policy: {csp()}\n")


if __name__ == "__main__":
    (WEB / "_headers").write_text(headers(), encoding="utf-8")
    print(f"wrote web/_headers ({len(script_hashes())} inline script hashes)")
