"""Generate worker/test/fixtures/parity.json: inputs + the Python reference's outputs for
Compare, Leaderboard and the decision helper. worker/test/parity.test.ts asserts the Worker's
port returns exactly the same; tests/test_control_plane.py fails if this file is stale.

    python scripts/export_parity_fixtures.py
"""
from __future__ import annotations

import copy
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from agentmeter.server.sessions import LEADERBOARD_SORTS, compare_s, cp_summary, leaderboard_s  # noqa: E402
from agentmeter.session.constraints import ConstraintError, evaluate_facts, load_rules  # noqa: E402

OUT = REPO / "worker" / "test" / "fixtures" / "parity.json"
GOLDEN = REPO / "tests" / "fixtures" / "golden_session" / "golden_session_results.json"


def _ident(sha: str, gpu: str, fp: str, provider: str, quant: str = "4bit") -> dict:
    return {"prepared_set_sha256": sha, "gpu_label": gpu, "settings_fingerprint": fp, "provider": provider,
            "settings": {"provider": provider, "quantization": quant, "max_new_tokens": 128}}


def _variant(base: dict, ident: dict, scale: float, provider: str, drop: tuple = (), labelled: bool = True,
             models: tuple = ()) -> dict:
    r = copy.deepcopy(base)
    r["session_identity"] = ident
    r["environment"]["provider"] = provider
    if provider != "mock":
        r["environment"]["gpu_name"] = ident.get("gpu_label", "NVIDIA L4")
    r["session"]["accuracy_available"] = labelled
    if models:
        r["per_model"] = [p for p in r["per_model"] if p["model"] in models]
    for i, pm in enumerate(r["per_model"]):
        e2e = pm["efficiency"]["end_to_end"]
        for k in list(e2e):
            if isinstance(e2e[k], (int, float)) and k not in drop:
                e2e[k] = e2e[k] * (scale + 0.07 * i)
            if k in drop:
                e2e[k] = None
        if e2e.get("mean_peak_vram_mb") is None and "mean_peak_vram_mb" not in drop:
            e2e["mean_peak_vram_mb"] = 900.0 * scale + 125 * i
    r["memory"] = {"per_model": [{"model": p["model"], "total_peak_mb": 5000.0 * scale + 333.3 * i,
                                  "weights_mb": 4100.0 + i} for i, p in enumerate(r["per_model"])]}
    r["cost_energy"] = {"per_model": [{"model": p["model"], "cost_per_1k_flows_usd": 0.0123456 * scale * (i + 1),
                                       "wh_per_flow": 0.0421 * scale + 0.001 * i, "wh_per_1k_flows": 42.1 * scale,
                                       "wh_per_flow_net_idle": 0.03 * scale} for i, p in enumerate(r["per_model"])]}
    return r


def build() -> dict:
    base = json.loads(GOLDEN.read_text(encoding="utf-8"))
    A, B = "a" * 64, "b" * 64
    specs = [  # (id, ident, scale, provider, drop, labelled, models)
        ("job_20261001_100000_" + "1" * 32, _ident(A, "NVIDIA L4", "fp1", "hf"), 1.0, "hf", (), True, ()),
        ("job_20261001_110000_" + "2" * 32, _ident(A, "NVIDIA L4", "fp1", "hf"), 1.3, "hf", (), True, ()),
        ("job_20261001_120000_" + "3" * 32, _ident(A, "NVIDIA L4", "fp2", "hf", "8bit"), 0.8, "hf", (), False, ()),
        ("job_20261001_130000_" + "4" * 32, _ident(A, "NVIDIA A100", "fp1", "hf"), 0.5, "hf", ("mean_latency_s",), True,
         ("Qwen/Qwen2.5-7B-Instruct",)),
        ("job_20261001_140000_" + "5" * 32, _ident(B, "Demo (no GPU)", "fpm", "mock"), 1.0, "mock", (), True, ()),
        ("job_20261001_150000_abcdef", {}, 1.1, "hf", (), True, ()),   # legacy id, no identity
    ]
    summaries = []
    for sid, ident, scale, prov, drop, lab, models in specs:
        res = _variant(base, ident, scale, prov, drop, lab, models)
        job = {"job_id": sid, "status": "done", "created_at": sid[4:19], "finished_at": sid[4:19],
               "models": [p["model"] for p in res["per_model"]], "run_name": "csv_runs/parity_1",
               "user": {"sub": "u1", "uname": "alice"}}
        summaries.append(cp_summary(job, res))
    newest_first = list(reversed(summaries))
    pairs = [(0, 1), (0, 2), (0, 3), (1, 4), (4, 5), (2, 3)]
    rules = load_rules()
    limits = [None, {}, {"max_mean_latency_s": "0.0004"}, {"max_mean_latency_s": "1", "max_p95_latency_s": 0.0001,
              "max_peak_vram_mb": "5200", "max_cost_per_1k_flows_usd": "0.02"}, {"max_peak_vram_mb": " 12000 "},
              {"max_cost_per_1k_flows_usd": "abc"}, {"max_peak_vram_mb": "-1"}, {"max_mean_latency_s": "1e-3"}]
    cons = []
    for s in summaries:
        for lim in limits:
            try:
                cons.append({"session": s["session_id"], "limits": lim, "out": evaluate_facts(s["facts"], lim, rules)})
            except ConstraintError as e:
                cons.append({"session": s["session_id"], "limits": lim, "error": str(e)})
    return {
        "note": "generated by scripts/export_parity_fixtures.py from the Python reference — do not edit",
        "summaries": summaries,
        "compare": [{"a": summaries[i]["session_id"], "b": summaries[j]["session_id"],
                     "out": compare_s(summaries[i], summaries[j])} for i, j in pairs],
        "leaderboard": {sort: leaderboard_s(newest_first, sort) for sort in LEADERBOARD_SORTS},
        "constraints": cons,
    }


def exported() -> str:
    return json.dumps(build(), indent=1, default=str) + "\n"


if __name__ == "__main__":
    OUT.write_text(exported(), encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)} ({OUT.stat().st_size} bytes)")
